### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by D-Nishimura808** [virtual-campus-tour/virtual-campus-tour.github.io#11]

**Comment by csonoda** [comment]
Your presentation should be approximately **10 minutes** long:

The **first three minutes** should: 

1. Introduce your team members 
2. Explain your coordination strategy (how often and where will you meet?)
3. Present the “Big Picture Vision” for your application.

The **next three minutes** should present your GitHub project page for the [Final Project Milestone M1](https://courses.ics.hawaii.edu/ics314f22/morea/final-project/experience-final-project-m1.html). Note: you do not have to have an HTML mockup for this presentation. As an alternative, you can embed pictures of paper-and-pencil mockups into this page. Here’s an example GitHub project page from Bowfolios: https://bowfolios.github.io/.

The **final three minutes** should present your M1 Project. Make sure the Project is organized according to the IDPM guidelines. Here’s an example Project Board from BowFolios: https://github.com/bowfolios/bowfolios/projects/3.

**Comment by csonoda** [comment]
Presentation was completed.
