### ISSUE TITLE
M1 Presentation

### ISSUE THREAD

**Issue by amandanitta** [virtual-campus-tour/virtual-campus-tour.github.io#12]
- Presentation for class describing team bonding/ team contract and M1 progress

**Comment by csonoda** [comment]
All presentations will be accomplished via the instructor’s laptop. You should Slack the instructor the URLs to any pages you want to present at the beginning of your presentation time. We will need the URL to your organization's home page as well as to your M1 Project page.

If you want to use slides to present your team, please do not send PPT files to load into PowerPoint; often the format gets messed up. Instead, put your presentations online so we can access them via a URL. Consider using [SpeakerDeck](https://speakerdeck.com/), [Haiku Deck](https://www.haikudeck.com/), [Reveal.JS](http://lab.hakim.se/reveal-js/#/) (or [slides.com](http://slides.com/)), [Prezi](https://prezi.com/) or something similar.
