### ISSUE TITLE
Code landing page

### ISSUE THREAD

**Issue by amandanitta** [virtual-campus-tour/virtual-campus-tour.github.io#25]
- visitor should understand what the site is about
- consider color blocked layout for the landing page
- landing page doesn't necessarily need a menu bar
- login portion needed

**Comment by D-Nishimura808** [comment]
Text color should be looked over and background image is too bright. Either change the picture or darken the image.

**Comment by D-Nishimura808** [comment]
Added Linear Gradient to Background Image
