### ISSUE TITLE
Code footer

### ISSUE THREAD

**Issue by amandanitta** [virtual-campus-tour/virtual-campus-tour.github.io#30]
code for the footer for the project

**Comment by csonoda** [comment]
**Code moved to different branch**
Worked on Footer

- Added Buttons
- Separated into columns
- Fixed Bottom Spacing

Mockup - **Changed: No longer same design**
https://docs.google.com/drawings/d/1An8ZGsRf2n4U5dGWDWn1AQC-DjqR4h9_erX3PjzTkyo/edit

![Image](https://user-images.githubusercontent.com/43054889/202022689-d60bab19-af7d-45d5-b012-4bd720e458d7.png)


New Issue: https://github.com/virtual-campus-tour/virtual-campus-tour/issues/3
