### ISSUE TITLE
create logo

### ISSUE THREAD

**Issue by amandanitta** [virtual-campus-tour/virtual-campus-tour.github.io#75]

**Comment by csonoda** [comment]
Current Progress on Logo

![Image](https://user-images.githubusercontent.com/43054889/204635308-cd3e7d50-4c51-4b04-9c56-59659a7b2b7b.png)
![Image](https://user-images.githubusercontent.com/43054889/204635310-e05bc1fa-f9e3-4588-b9cf-d8add84c598e.png)
![Image](https://user-images.githubusercontent.com/43054889/204635309-63fd48d0-7dea-45e1-a460-9f9ef30278de.png)
